-- Consolidated schema built from original migrations:
-- 0001_initial.sql
-- 0002_bybit_integration.sql
-- 0003_bybit_pnl.sql
-- 0004_bybit_pnl_unique.sql
-- 0005_bybit_raw_trades_unique.sql
-- 0006_trades_unique_external.sql
-- 0007_trades_trade_details.sql

create extension if not exists "uuid-ossp";

create type semaforo_estado as enum ('Verde', 'Amarillo', 'Rojo', 'Indeterminado');

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  email text not null unique,
  display_name text,
  timezone text not null default 'America/New_York',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_plans (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  version integer not null,
  patrimonio numeric(14,2) not null,
  r_pct numeric(5,2) not null check (r_pct > 0 and r_pct <= 10),
  sl_diario_r numeric(6,2) not null,
  sl_semanal_r numeric(6,2) not null,
  horarios jsonb not null,
  no_trade_days text[] not null default '{}',
  apalancamiento_btceth_max numeric(5,2) not null,
  apalancamiento_alts_max numeric(5,2) not null,
  fase_actual text not null,
  nivel_actual text not null,
  notes text,
  effective_from timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, version)
);

create table public.global_semaforo_daily (
  id uuid primary key default uuid_generate_v4(),
  fecha date not null unique,
  estado semaforo_estado not null,
  indicadores_json jsonb not null,
  explicacion_gpt text,
  computed_at timestamptz not null default now(),
  retries integer not null default 0
);

create table public.trades (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  symbol text not null,
  side text not null check (side in ('long', 'short', 'buy', 'sell')),
  type text not null check (type in ('spot', 'perp')),
  exchange text,
  entry numeric(18,8) not null,
  sl numeric(18,8) not null,
  tp_json jsonb,
  leverage numeric(10,2) not null default 1,
  size_nominal numeric(18,4) not null,
  risk_monetario numeric(14,2) not null,
  risk_en_r numeric(10,2) not null,
  open_time timestamptz not null default now(),
  close_time timestamptz,
  pnl_monetario numeric(14,2),
  pnl_r numeric(10,2),
  cumplimiento_flags text[] not null default '{}',
  status text not null default 'open' check (status in ('open', 'closed', 'invalid')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.metrics_daily (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  fecha date not null,
  pnl_r_dia numeric(10,2) not null default 0,
  pnl_r_semana numeric(10,2) not null default 0,
  tp_count integer not null default 0,
  sl_hits_48h integer not null default 0,
  streak_dias_verdes integer not null default 0,
  cumplimiento_pct numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, fecha)
);

create table public.gamification_state (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  xp integer not null default 0,
  level_perfil integer not null default 1,
  badges_json jsonb not null default '[]'::jsonb,
  streak_cumplimiento integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table public.emotional_logs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  log_date date not null,
  estado_antes smallint not null check (estado_antes between 1 and 5),
  estado_despues smallint not null check (estado_despues between 1 and 5),
  confianza smallint not null check (confianza between 1 and 5),
  cansancio smallint not null check (cansancio between 1 and 5),
  claridad smallint not null check (claridad between 1 and 5),
  emocion_dominante text,
  reflexion text,
  gratitud text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create table public.admin_notifications (
  id uuid primary key default uuid_generate_v4(),
  categoria text not null,
  message text not null,
  metadata jsonb,
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz
);

-- RLS
alter table public.profiles enable row level security;
alter table public.user_plans enable row level security;
alter table public.trades enable row level security;
alter table public.metrics_daily enable row level security;
alter table public.gamification_state enable row level security;
alter table public.audit_logs enable row level security;
alter table public.emotional_logs enable row level security;

create policy "Users can view their profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users manage their profile" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can read their plans" on public.user_plans
  for select using (auth.uid() = user_id);

create policy "Users can insert plans" on public.user_plans
  for insert with check (auth.uid() = user_id);

create policy "Users can update plans" on public.user_plans
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users manage their trades" on public.trades
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can view their metrics" on public.metrics_daily
  for select using (auth.uid() = user_id);

create policy "Users can upsert their metrics" on public.metrics_daily
  for insert with check (auth.uid() = user_id);

create policy "Users can update their metrics" on public.metrics_daily
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can view their gamification" on public.gamification_state
  for select using (auth.uid() = user_id);

create policy "Users can insert their gamification" on public.gamification_state
  for insert with check (auth.uid() = user_id);

create policy "Users can update their gamification" on public.gamification_state
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can write self audit logs" on public.audit_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can manage their emotional logs" on public.emotional_logs
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index idx_trades_user_status on public.trades(user_id, status);
create index idx_metrics_daily_user_fecha on public.metrics_daily(user_id, fecha);
create index idx_global_semaforo_fecha on public.global_semaforo_daily(fecha);
create index idx_emotional_logs_user_fecha on public.emotional_logs(user_id, log_date);
create table public.bybit_connections (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  api_key_cipher text not null,
  api_secret_cipher text not null,
  status text not null default 'active' check (status in ('active', 'paused')),
  last_synced_at timestamptz,
  last_cursor text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table public.bybit_raw_trades (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  connection_id uuid not null references public.bybit_connections(id) on delete cascade,
  exec_id text not null,
  order_id text,
  payload jsonb not null,
  traded_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, exec_id)
);

alter table public.trades
  add column external_id text;

create unique index if not exists idx_trades_user_external on public.trades(user_id, external_id)
  where external_id is not null;

create index idx_bybit_connections_user on public.bybit_connections(user_id);
create index idx_bybit_raw_trades_user on public.bybit_raw_trades(user_id);

alter table public.bybit_connections enable row level security;
alter table public.bybit_raw_trades enable row level security;

create policy "Users manage their Bybit connection" on public.bybit_connections
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users manage their Bybit trades" on public.bybit_raw_trades
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create table public.bybit_pnl_history (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id text not null,
  symbol text not null,
  side text,
  qty numeric(18,8),
  realised_pnl numeric(14,4),
  fee numeric(14,4),
  avg_entry_price numeric(18,8),
  avg_exit_price numeric(18,8),
  closed_size numeric(18,8),
  leverage numeric(10,4),
  closed_at timestamptz not null,
  raw jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, order_id, closed_at)
);

create table public.account_balance_snapshots (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null default 'bybit',
  balance numeric(18,8) not null,
  equity numeric(18,8),
  available_balance numeric(18,8),
  captured_at timestamptz not null default now()
);

create index idx_bybit_pnl_user_closed_at on public.bybit_pnl_history(user_id, closed_at);
create index idx_account_balance_user_time on public.account_balance_snapshots(user_id, captured_at desc);

alter table public.bybit_pnl_history enable row level security;
alter table public.account_balance_snapshots enable row level security;

create policy "Users manage their Bybit PnL" on public.bybit_pnl_history
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users manage their balance snapshots" on public.account_balance_snapshots
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
alter table public.bybit_pnl_history
  add constraint bybit_pnl_history_user_order_closed_key unique (user_id, order_id, closed_at);
alter table public.bybit_raw_trades
  add constraint bybit_raw_trades_user_exec_key unique (user_id, exec_id);
alter table public.trades
  add constraint trades_user_external_key unique (user_id, external_id);
alter table public.trades
  add column if not exists quantity numeric(18,8),
  add column if not exists exit_price numeric(18,8),
  add column if not exists close_volume numeric(18,8);

comment on column public.trades.quantity is 'Contracts/size associated to the trade';
comment on column public.trades.exit_price is 'Average exit price when the trade is closed';
comment on column public.trades.close_volume is 'Notional value at close time (quantity * exit price)';
